version: '3.4'

services:
  api_getway:
    image: ${DOCKER_REGISTRY-}apigetway
    build:
      context: .
      dockerfile: API_Getway/Dockerfile

  api_generic:
    image: ${DOCKER_REGISTRY-}apigeneric
    build:
      context: .
      dockerfile: API_Generic/Dockerfile


  api_login:
    image: ${DOCKER_REGISTRY-}apilogin
    build:
      context: .
      dockerfile: API_Login/Dockerfile


  api_registrations:
    image: ${DOCKER_REGISTRY-}apiregistrations
    build:
      context: .
      dockerfile: API_Registrations/Dockerfile

