version: '3.7'

services:
  api_user:
    image: ${DOCKER_REGISTRY-}apiuser
    build:
      context: .
      dockerfile: API_User/Dockerfile

  api_login:
    image: ${DOCKER_REGISTRY-}apilogin
    build:
      context: .
      dockerfile: API_Login/Dockerfile


  api_getway:
    image: ${DOCKER_REGISTRY-}apigetway
    build:
      context: .
      dockerfile: API_Getway/Dockerfile


  api_generic:
    image: ${DOCKER_REGISTRY-}apigeneric
    build:
      context: .
      dockerfile: API_Generic/Dockerfile

