// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Users_Database
{
    public partial class APIResponse
    {
        public int Id { get; set; }
        public string? Response { get; set; }
        public int? RequestId { get; set; }
        public DateTime? ResponseDate { get; set; }
        public bool? ReponseStatus { get; set; }
        public int? UserId { get; set; }
    }
}