// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Users_Database
{
    public partial class AdminOrgProduct
    {
        public AdminOrgProduct()
        {
            AdminBranch = new HashSet<AdminBranch>();
            AdminCompany = new HashSet<AdminCompany>();
            AdminRole = new HashSet<AdminRole>();
            AdminUser = new HashSet<AdminUser>();
            AdminUserBranch = new HashSet<AdminUserBranch>();
        }

        public int OrgProdId { get; set; }
        public int Orgid { get; set; }
        public int ProdId { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual AdminOrganization Org { get; set; } = null!;
        public virtual AdminProduct Prod { get; set; } = null!;
        public virtual ICollection<AdminBranch> AdminBranch { get; set; }
        public virtual ICollection<AdminCompany> AdminCompany { get; set; }
        public virtual ICollection<AdminRole> AdminRole { get; set; }
        public virtual ICollection<AdminUser> AdminUser { get; set; }
        public virtual ICollection<AdminUserBranch> AdminUserBranch { get; set; }
    }
}