// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Users_Database.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable enable

namespace Users_Database
{
    public partial class User_DbContext : DbContext
    {
        public User_DbContext()
        {
        }

        public User_DbContext(DbContextOptions<User_DbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AdminBranch> AdminBranch { get; set; } = null!;
        public virtual DbSet<AdminCompany> AdminCompany { get; set; } = null!;
        public virtual DbSet<AdminMenu> AdminMenu { get; set; } = null!;
        public virtual DbSet<AdminOrgProduct> AdminOrgProduct { get; set; } = null!;
        public virtual DbSet<AdminOrganization> AdminOrganization { get; set; } = null!;
        public virtual DbSet<AdminProduct> AdminProduct { get; set; } = null!;
        public virtual DbSet<AdminRights> AdminRights { get; set; } = null!;
        public virtual DbSet<AdminRole> AdminRole { get; set; } = null!;
        public virtual DbSet<AdminUser> AdminUser { get; set; } = null!;
        public virtual DbSet<AdminUserBranch> AdminUserBranch { get; set; } = null!;
        public virtual DbSet<StatusNotification> StatusNotification { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.AdminBranchConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AdminCompanyConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AdminMenuConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AdminOrgProductConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AdminOrganizationConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AdminProductConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AdminRightsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AdminRoleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AdminUserConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AdminUserBranchConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.StatusNotificationConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
