// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Masters_Database.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable enable

namespace Masters_Database
{
    public partial class Master_DbContext : DbContext
    {
        public Master_DbContext()
        {
        }

        public Master_DbContext(DbContextOptions<Master_DbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MasterCity> MasterCity { get; set; } = null!;
        public virtual DbSet<MasterCountry> MasterCountry { get; set; } = null!;
        public virtual DbSet<MasterCurrency> MasterCurrency { get; set; } = null!;
        public virtual DbSet<MasterState> MasterState { get; set; } = null!;
        public virtual DbSet<MasterTimeZone> MasterTimeZone { get; set; } = null!;
        public virtual DbSet<MastersContinent> MastersContinent { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.MasterCityConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MasterCountryConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MasterCurrencyConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MasterStateConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MasterTimeZoneConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MastersContinentConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
