// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Users_Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Users_Database.Configurations
{
    public partial class APIResponseConfiguration : IEntityTypeConfiguration<APIResponse>
    {
        public void Configure(EntityTypeBuilder<APIResponse> entity)
        {
            entity.Property(e => e.ResponseDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<APIResponse> entity);
    }
}
