// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Users_Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Users_Database.Configurations
{
    public partial class AdminUserBranchConfiguration : IEntityTypeConfiguration<AdminUserBranch>
    {
        public void Configure(EntityTypeBuilder<AdminUserBranch> entity)
        {
            entity.HasKey(e => e.Userbranchid);

            entity.HasIndex(e => e.BranchId, "IX_AdminUserBranch_BranchId");

            entity.HasIndex(e => e.CompanyId, "IX_AdminUserBranch_CompanyId");

            entity.HasIndex(e => e.OrgProdId, "IX_AdminUserBranch_OrgProdId");

            entity.HasIndex(e => e.RoleId, "IX_AdminUserBranch_RoleId");

            entity.HasIndex(e => e.UserId, "IX_AdminUserBranch_UserId");

            entity.Property(e => e.IsDeleted).HasDefaultValueSql("((0))");

            entity.HasOne(d => d.Branch)
                .WithMany(p => p.AdminUserBranch)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminUserBranch_AdminBranch");

            entity.HasOne(d => d.Company)
                .WithMany(p => p.AdminUserBranch)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminUserBranch_AdminCompany");

            entity.HasOne(d => d.OrgProd)
                .WithMany(p => p.AdminUserBranch)
                .HasForeignKey(d => d.OrgProdId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminUserBranch_AdminOrgProduct");

            entity.HasOne(d => d.Role)
                .WithMany(p => p.AdminUserBranch)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminUserBranch_AdminRole");

            entity.HasOne(d => d.User)
                .WithMany(p => p.AdminUserBranch)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminUserBranch_AdminUser");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AdminUserBranch> entity);
    }
}
