// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Application_Database
{
    public partial class AdminRole
    {
        public AdminRole()
        {
            AdminRights = new HashSet<AdminRights>();
            AdminUserBranch = new HashSet<AdminUserBranch>();
        }

        public int RoleId { get; set; }
        public int? OrgProdId { get; set; }
        public string RoleName { get; set; } = null!;
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? DeletedBy { get; set; }
        public DateTime? DeletedDate { get; set; }

        public virtual AdminOrgProduct? OrgProd { get; set; }
        public virtual ICollection<AdminRights> AdminRights { get; set; }
        public virtual ICollection<AdminUserBranch> AdminUserBranch { get; set; }
    }
}