// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Users_Database
{
    public partial class AdminUserBranch
    {
        public int Userbranchid { get; set; }
        public int OrgProdId { get; set; }
        public int UserId { get; set; }
        public int CompanyId { get; set; }
        public int BranchId { get; set; }
        public int RoleId { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual AdminBranch Branch { get; set; } = null!;
        public virtual AdminCompany Company { get; set; } = null!;
        public virtual AdminOrgProduct OrgProd { get; set; } = null!;
        public virtual AdminRole Role { get; set; } = null!;
        public virtual AdminUser User { get; set; } = null!;
    }
}