// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Application_Database
{
    public partial class AdminOrgProduct
    {
        public int OrgProdId { get; set; }
        public int Orgid { get; set; }
        public int ProdId { get; set; }

        public virtual AdminOrganization Org { get; set; } = default!;
        public virtual AdminProduct Prod { get; set; } = default!;
    }
}