// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Users_Database
{
    public partial class AdminUser
    {
        public AdminUser()
        {
            AdminUserBranch = new HashSet<AdminUserBranch>();
        }

        public int UserId { get; set; }
        public int OrgProdId { get; set; }
        public string LoginMail { get; set; } = null!;
        public string LoginPassword { get; set; } = null!;
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? DeletedBy { get; set; }
        public DateTime? DeletedDate { get; set; }

        public virtual AdminOrgProduct OrgProd { get; set; } = null!;
        public virtual ICollection<AdminUserBranch> AdminUserBranch { get; set; }
    }
}