// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Application_Database
{
    public partial class sp_AdminOrganization_InsertResult
    {
        public string MSG { get; set; } = default!;
    }
}
