// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Application_Database
{
    public partial class sp_GenerateSPforInsertUpdateDeleteResult
    {
        public string TableQualifier { get; set; } = default!;
        public string TableOwner { get; set; } = default!;
        public string TableName { get; set; } = default!;
        public string ColumnName { get; set; } = default!;
        public int? KeySeq { get; set; }
        public string PKName { get; set; } = default!;
    }
}
