// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application_Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Application_Database.Configurations
{
    public partial class AdminRoleConfiguration : IEntityTypeConfiguration<AdminRole>
    {
        public void Configure(EntityTypeBuilder<AdminRole> entity)
        {
            entity.HasKey(e => e.RoleId);

            entity.HasIndex(e => e.OrgProdId, "IX_AdminRole_OrgProdId");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.DeletedDate).HasColumnType("datetime");

            entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");

            entity.Property(e => e.IsDeleted).HasDefaultValueSql("((0))");

            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.Property(e => e.RoleName).HasMaxLength(50);

            entity.HasOne(d => d.OrgProd)
                .WithMany(p => p.AdminRole)
                .HasForeignKey(d => d.OrgProdId)
                .HasConstraintName("FK_AdminRole_AdminOrgProduct");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AdminRole> entity);
    }
}
