// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application_Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Application_Database.Configurations
{
    public partial class AdminOrgProductConfiguration : IEntityTypeConfiguration<AdminOrgProduct>
    {
        public void Configure(EntityTypeBuilder<AdminOrgProduct> entity)
        {
            entity.HasKey(e => e.OrgProdId);

            entity.HasIndex(e => e.Orgid, "IX_AdminOrgProduct_Orgid");

            entity.HasIndex(e => e.ProdId, "IX_AdminOrgProduct_ProdId");

            entity.Property(e => e.IsDeleted).HasDefaultValueSql("((0))");

            entity.HasOne(d => d.Org)
                .WithMany(p => p.AdminOrgProduct)
                .HasForeignKey(d => d.Orgid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminOrgProduct_AdminOrganization");

            entity.HasOne(d => d.Prod)
                .WithMany(p => p.AdminOrgProduct)
                .HasForeignKey(d => d.ProdId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminOrgProduct_AdminProduct");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AdminOrgProduct> entity);
    }
}
