// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application_Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Application_Database.Configurations
{
    public partial class AdminRightsConfiguration : IEntityTypeConfiguration<AdminRights>
    {
        public void Configure(EntityTypeBuilder<AdminRights> entity)
        {
            entity.HasKey(e => e.RightId);

            entity.Property(e => e.AddAccess).HasDefaultValueSql("((0))");

            entity.Property(e => e.DeleteAccess).HasDefaultValueSql("((0))");

            entity.Property(e => e.EditAccess).HasDefaultValueSql("((0))");

            entity.Property(e => e.ViewAccess).HasDefaultValueSql("((0))");

            entity.HasOne(d => d.Menu)
                .WithMany(p => p.AdminRights)
                .HasForeignKey(d => d.MenuId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminRights_AdminMenu");

            entity.HasOne(d => d.Role)
                .WithMany(p => p.AdminRights)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminRights_AdminRole");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AdminRights> entity);
    }
}
