// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application_Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Application_Database.Configurations
{
    public partial class AdminCompanyConfiguration : IEntityTypeConfiguration<AdminCompany>
    {
        public void Configure(EntityTypeBuilder<AdminCompany> entity)
        {
            entity.HasKey(e => e.CompId);

            entity.HasIndex(e => e.OrgProdId, "IX_AdminCompany_OrgProdId");

            entity.Property(e => e.Address1).HasMaxLength(500);

            entity.Property(e => e.Address2).HasMaxLength(500);

            entity.Property(e => e.Address3).HasMaxLength(500);

            entity.Property(e => e.CompName).HasMaxLength(200);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.DeletedDate).HasColumnType("datetime");

            entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");

            entity.Property(e => e.IsDeleted).HasDefaultValueSql("((0))");

            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.Property(e => e.TelephoneNo).HasMaxLength(50);

            entity.HasOne(d => d.OrgProd)
                .WithMany(p => p.AdminCompany)
                .HasForeignKey(d => d.OrgProdId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminCompany_AdminOrgProduct");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AdminCompany> entity);
    }
}
