// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application_Database;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Application_Database.Configurations
{
    public partial class APIRequestConfiguration : IEntityTypeConfiguration<APIRequest>
    {
        public void Configure(EntityTypeBuilder<APIRequest> entity)
        {
            entity.Property(e => e.Path).HasMaxLength(100);

            entity.Property(e => e.QueryString).HasMaxLength(500);

            entity.Property(e => e.RequestDate).HasColumnType("datetime");

            entity.Property(e => e.Scheme).HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<APIRequest> entity);
    }
}
