// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application_Database;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Application_Database.Configurations
{
    public partial class StatusNotificationConfiguration : IEntityTypeConfiguration<StatusNotification>
    {
        public void Configure(EntityTypeBuilder<StatusNotification> entity)
        {
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            entity.Property(e => e.FailDetails).HasMaxLength(2000);

            entity.Property(e => e.MsgBody).IsRequired();

            entity.Property(e => e.MsgCC).HasMaxLength(500);

            entity.Property(e => e.MsgFrom).HasMaxLength(200);

            entity.Property(e => e.MsgSatus)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.MsgSubject)
                .IsRequired()
                .HasMaxLength(1000);

            entity.Property(e => e.MsgTo).HasMaxLength(500);

            entity.Property(e => e.MsgType)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StatusNotification> entity);
    }
}
