// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application_Database.Configurations;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
#nullable enable

#nullable disable

namespace Application_Database
{
    public partial class APP_DbContext : DbContext
    {
        public APP_DbContext()
        {
        }

        public APP_DbContext(DbContextOptions<APP_DbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<APIRequest> APIRequest { get; set; }
        public virtual DbSet<APIResponse> APIResponse { get; set; }
        public virtual DbSet<AdminOrgProduct> AdminOrgProduct { get; set; }
        public virtual DbSet<AdminOrganization> AdminOrganization { get; set; }
        public virtual DbSet<AdminProduct> AdminProduct { get; set; }
        public virtual DbSet<StatusNotification> StatusNotification { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.APIRequestConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.APIResponseConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AdminOrgProductConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AdminOrganizationConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AdminProductConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.StatusNotificationConfiguration());
            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
