// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Application_Database
{
    public partial class TblApiResponse
    {
        public int Id { get; set; }
        public string Filename { get; set; }
        public int? Userid { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public bool? Apistauts { get; set; }
        public DateTime? Apidate { get; set; }
    }
}