// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Application_Database
{
    public partial class TblNotification
    {
        public int Id { get; set; }
        public string MsgType { get; set; }
        public string MsgFrom { get; set; }
        public string MsgTo { get; set; }
        public string MsgCc { get; set; }
        public string MsgSubject { get; set; }
        public string MsgBody { get; set; }
        public string MsgSatus { get; set; }
        public string FailDetails { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}