// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Application_Database
{
    public partial class TblRolemaster
    {
        public TblRolemaster()
        {
            TblRightmaster = new HashSet<TblRightmaster>();
        }

        public int RoleId { get; set; }
        public string RoleNmae { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool RecordLocked { get; set; }
        public int RecordLockedBy { get; set; }
        public DateTime RecordLockedOn { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
        public int DeletedBy { get; set; }
        public DateTime DeletedOn { get; set; }

        public virtual ICollection<TblRightmaster> TblRightmaster { get; set; }
    }
}