// <auto-generated />
using Application_Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application_Database.Migrations
{
    [DbContext(typeof(APP_DbContext))]
    [Migration("20210508113334_NotificationTable_UpdateNull")]
    partial class NotificationTable_UpdateNull
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Application_Domain.Demo_Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Demo_Customer");
                });

            modelBuilder.Entity("Application_Domain.NotficationCls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FailDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FailDetails");

                    b.Property<string>("MsgBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MsgBody");

                    b.Property<string>("MsgCC")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MsgCC");

                    b.Property<string>("MsgFrom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MsgFrom");

                    b.Property<int>("MsgSatus")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("MsgSatus");

                    b.Property<string>("MsgSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MsgSubject");

                    b.Property<string>("MsgTo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MsgTo");

                    b.Property<int>("MsgType")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("MsgType");

                    b.HasKey("Id");

                    b.ToTable("tbl_Notification");
                });
#pragma warning restore 612, 618
        }
    }
}
