// <auto-generated />
using System;
using Application_Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application_Database.Migrations
{
    [DbContext(typeof(APP_DbContext))]
    partial class APP_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Application_Domain.NotficationCls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FailDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FailDetails");

                    b.Property<string>("MsgBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MsgBody");

                    b.Property<string>("MsgCC")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MsgCC");

                    b.Property<string>("MsgFrom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MsgFrom");

                    b.Property<int>("MsgSatus")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("MsgSatus");

                    b.Property<string>("MsgSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MsgSubject");

                    b.Property<string>("MsgTo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MsgTo");

                    b.Property<int>("MsgType")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("MsgType");

                    b.HasKey("Id");

                    b.ToTable("tbl_Notification");
                });

            modelBuilder.Entity("Application_Domain.UserConfig.rights_cls", b =>
                {
                    b.Property<int>("RightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RightId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Add")
                        .HasColumnType("bit")
                        .HasColumnName("Add");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Delete")
                        .HasColumnType("bit")
                        .HasColumnName("Delete");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Edit")
                        .HasColumnType("bit")
                        .HasColumnName("Edit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("MenuId");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RecordLocked")
                        .HasColumnType("bit");

                    b.Property<int>("RecordLockedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordLockedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.Property<bool>("View")
                        .HasColumnType("bit")
                        .HasColumnName("View");

                    b.HasKey("RightId");

                    b.HasIndex("RoleId");

                    b.ToTable("tbl_rightmaster");
                });

            modelBuilder.Entity("Application_Domain.UserConfig.role_cls", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RecordLocked")
                        .HasColumnType("bit");

                    b.Property<int>("RecordLockedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordLockedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleNmae")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RoleNmae");

                    b.HasKey("RoleId");

                    b.ToTable("tbl_rolemaster");
                });

            modelBuilder.Entity("Application_Domain.UserConfig.user_cls", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("EmailId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Password");

                    b.Property<bool>("RecordLocked")
                        .HasColumnType("bit");

                    b.Property<int>("RecordLockedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordLockedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UserName");

                    b.HasKey("UserId");

                    b.ToTable("tbl_usermaster");
                });

            modelBuilder.Entity("Application_Domain.UserConfig.rights_cls", b =>
                {
                    b.HasOne("Application_Domain.UserConfig.role_cls", "RoleDetails")
                        .WithMany("RightDetails")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_RoleRights_RoleId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("RoleDetails");
                });

            modelBuilder.Entity("Application_Domain.UserConfig.role_cls", b =>
                {
                    b.Navigation("RightDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
